export const CHESSGROUND_CONTAINER_CLASS = "chessgroundMarkdownContainer";
export const CHESSGROUND_CLASS = "chessgroundMarkdown";
export const CHESSGROUND_INFO_CLASS = "chessgroundInfo";
export const CHESSGROUND_MOVES_CLASS = "chessgroundMoves";
export const DEFAULT_BOARD_GEOMETRY = "is2d";
export const DEFAULT_PIECE_SET: PieceSet = "merida";
export const DEFAULT_ARROW_COLOR = "green";
export const DEFAULT_SQUARE_COLOR = "green";
export const DEFAULT_MOVE_DELAY_MILLISECONDS = 300;